// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package hr.actions;

import com.mendix.core.Core;
import com.mendix.logging.ILogNode;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;
import com.mendix.webui.CustomJavaAction;
import java.util.List;

public class RetrieveAdvancedXpath extends CustomJavaAction<java.util.List<IMendixObject>>
{
	private java.lang.String Xpath;
	private java.lang.String ResultEntity;

	public RetrieveAdvancedXpath(IContext context, java.lang.String Xpath, java.lang.String ResultEntity)
	{
		super(context);
		this.Xpath = Xpath;
		this.ResultEntity = ResultEntity;
	}

	@Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
        List<IMendixObject> result = null;
        result = Core.retrieveXPathQuery(getContext(), this.Xpath);
        if (!result.isEmpty() && !result.get(0).getMetaObject().getName().equals(this.ResultEntity)) {
            throw new MendixRuntimeException(String.format("Unexpected result entity: %s vs %s",
                    result.get(0).getMetaObject().getName(), this.ResultEntity));
        }
        return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "RetrieveAdvancedXpath";
	}

	// BEGIN EXTRA CODE
    private final ILogNode logger = Core.getLogger(this.getClass().getName());
	// END EXTRA CODE
}
