// This file was generated by Mendix Modeler 7.0.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package csvservices.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the CsvServices module

	public static java.lang.String getCSV_SERVICES_VERSION()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("CsvServices.CSV_SERVICES_VERSION");
	}
}