// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package hr.proxies;

public class DepartmentSummary
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject departmentSummaryMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Hr.DepartmentSummary";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		MaxDateOfBirth("MaxDateOfBirth"),
		MinDateOfBirth("MinDateOfBirth"),
		TotalSalary("TotalSalary"),
		AvgSalary("AvgSalary"),
		MinSalary("MinSalary");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DepartmentSummary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Hr.DepartmentSummary"));
	}

	protected DepartmentSummary(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject departmentSummaryMendixObject)
	{
		if (departmentSummaryMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Hr.DepartmentSummary", departmentSummaryMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Hr.DepartmentSummary");

		this.departmentSummaryMendixObject = departmentSummaryMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DepartmentSummary.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static hr.proxies.DepartmentSummary initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return hr.proxies.DepartmentSummary.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static hr.proxies.DepartmentSummary initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new hr.proxies.DepartmentSummary(context, mendixObject);
	}

	public static hr.proxies.DepartmentSummary load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return hr.proxies.DepartmentSummary.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of MaxDateOfBirth
	 */
	public final java.util.Date getMaxDateOfBirth()
	{
		return getMaxDateOfBirth(getContext());
	}

	/**
	 * @param context
	 * @return value of MaxDateOfBirth
	 */
	public final java.util.Date getMaxDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.MaxDateOfBirth.toString());
	}

	/**
	 * Set value of MaxDateOfBirth
	 * @param maxdateofbirth
	 */
	public final void setMaxDateOfBirth(java.util.Date maxdateofbirth)
	{
		setMaxDateOfBirth(getContext(), maxdateofbirth);
	}

	/**
	 * Set value of MaxDateOfBirth
	 * @param context
	 * @param maxdateofbirth
	 */
	public final void setMaxDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date maxdateofbirth)
	{
		getMendixObject().setValue(context, MemberNames.MaxDateOfBirth.toString(), maxdateofbirth);
	}

	/**
	 * @return value of MinDateOfBirth
	 */
	public final java.util.Date getMinDateOfBirth()
	{
		return getMinDateOfBirth(getContext());
	}

	/**
	 * @param context
	 * @return value of MinDateOfBirth
	 */
	public final java.util.Date getMinDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.MinDateOfBirth.toString());
	}

	/**
	 * Set value of MinDateOfBirth
	 * @param mindateofbirth
	 */
	public final void setMinDateOfBirth(java.util.Date mindateofbirth)
	{
		setMinDateOfBirth(getContext(), mindateofbirth);
	}

	/**
	 * Set value of MinDateOfBirth
	 * @param context
	 * @param mindateofbirth
	 */
	public final void setMinDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date mindateofbirth)
	{
		getMendixObject().setValue(context, MemberNames.MinDateOfBirth.toString(), mindateofbirth);
	}

	/**
	 * @return value of TotalSalary
	 */
	public final java.math.BigDecimal getTotalSalary()
	{
		return getTotalSalary(getContext());
	}

	/**
	 * @param context
	 * @return value of TotalSalary
	 */
	public final java.math.BigDecimal getTotalSalary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.TotalSalary.toString());
	}

	/**
	 * Set value of TotalSalary
	 * @param totalsalary
	 */
	public final void setTotalSalary(java.math.BigDecimal totalsalary)
	{
		setTotalSalary(getContext(), totalsalary);
	}

	/**
	 * Set value of TotalSalary
	 * @param context
	 * @param totalsalary
	 */
	public final void setTotalSalary(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal totalsalary)
	{
		getMendixObject().setValue(context, MemberNames.TotalSalary.toString(), totalsalary);
	}

	/**
	 * @return value of AvgSalary
	 */
	public final java.math.BigDecimal getAvgSalary()
	{
		return getAvgSalary(getContext());
	}

	/**
	 * @param context
	 * @return value of AvgSalary
	 */
	public final java.math.BigDecimal getAvgSalary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.AvgSalary.toString());
	}

	/**
	 * Set value of AvgSalary
	 * @param avgsalary
	 */
	public final void setAvgSalary(java.math.BigDecimal avgsalary)
	{
		setAvgSalary(getContext(), avgsalary);
	}

	/**
	 * Set value of AvgSalary
	 * @param context
	 * @param avgsalary
	 */
	public final void setAvgSalary(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal avgsalary)
	{
		getMendixObject().setValue(context, MemberNames.AvgSalary.toString(), avgsalary);
	}

	/**
	 * @return value of MinSalary
	 */
	public final java.math.BigDecimal getMinSalary()
	{
		return getMinSalary(getContext());
	}

	/**
	 * @param context
	 * @return value of MinSalary
	 */
	public final java.math.BigDecimal getMinSalary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.MinSalary.toString());
	}

	/**
	 * Set value of MinSalary
	 * @param minsalary
	 */
	public final void setMinSalary(java.math.BigDecimal minsalary)
	{
		setMinSalary(getContext(), minsalary);
	}

	/**
	 * Set value of MinSalary
	 * @param context
	 * @param minsalary
	 */
	public final void setMinSalary(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal minsalary)
	{
		getMendixObject().setValue(context, MemberNames.MinSalary.toString(), minsalary);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return departmentSummaryMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final hr.proxies.DepartmentSummary that = (hr.proxies.DepartmentSummary) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Hr.DepartmentSummary";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
