// This file was generated by Mendix Modeler.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package hr.proxies;

public class Employee
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject employeeMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Hr.Employee";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		DateOfBirth("DateOfBirth"),
		Salary("Salary"),
		DateOfHire("DateOfHire"),
		Bonus("Bonus"),
		EmployeeId("EmployeeId"),
		Employee_Department("Hr.Employee_Department");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Employee(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Hr.Employee"));
	}

	protected Employee(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject employeeMendixObject)
	{
		if (employeeMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Hr.Employee", employeeMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Hr.Employee");

		this.employeeMendixObject = employeeMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Employee.load(IContext, IMendixIdentifier)' instead.
	 */
	@Deprecated
	public static hr.proxies.Employee initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return hr.proxies.Employee.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static hr.proxies.Employee initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new hr.proxies.Employee(context, mendixObject);
	}

	public static hr.proxies.Employee load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return hr.proxies.Employee.initialize(context, mendixObject);
	}

	public static java.util.List<hr.proxies.Employee> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<hr.proxies.Employee> result = new java.util.ArrayList<hr.proxies.Employee>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Hr.Employee" + xpathConstraint))
			result.add(hr.proxies.Employee.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth()
	{
		return getDateOfBirth(getContext());
	}

	/**
	 * @param context
	 * @return value of DateOfBirth
	 */
	public final java.util.Date getDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateOfBirth.toString());
	}

	/**
	 * Set value of DateOfBirth
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(java.util.Date dateofbirth)
	{
		setDateOfBirth(getContext(), dateofbirth);
	}

	/**
	 * Set value of DateOfBirth
	 * @param context
	 * @param dateofbirth
	 */
	public final void setDateOfBirth(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateofbirth)
	{
		getMendixObject().setValue(context, MemberNames.DateOfBirth.toString(), dateofbirth);
	}

	/**
	 * @return value of Salary
	 */
	public final java.math.BigDecimal getSalary()
	{
		return getSalary(getContext());
	}

	/**
	 * @param context
	 * @return value of Salary
	 */
	public final java.math.BigDecimal getSalary(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Salary.toString());
	}

	/**
	 * Set value of Salary
	 * @param salary
	 */
	public final void setSalary(java.math.BigDecimal salary)
	{
		setSalary(getContext(), salary);
	}

	/**
	 * Set value of Salary
	 * @param context
	 * @param salary
	 */
	public final void setSalary(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal salary)
	{
		getMendixObject().setValue(context, MemberNames.Salary.toString(), salary);
	}

	/**
	 * @return value of DateOfHire
	 */
	public final java.util.Date getDateOfHire()
	{
		return getDateOfHire(getContext());
	}

	/**
	 * @param context
	 * @return value of DateOfHire
	 */
	public final java.util.Date getDateOfHire(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.DateOfHire.toString());
	}

	/**
	 * Set value of DateOfHire
	 * @param dateofhire
	 */
	public final void setDateOfHire(java.util.Date dateofhire)
	{
		setDateOfHire(getContext(), dateofhire);
	}

	/**
	 * Set value of DateOfHire
	 * @param context
	 * @param dateofhire
	 */
	public final void setDateOfHire(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date dateofhire)
	{
		getMendixObject().setValue(context, MemberNames.DateOfHire.toString(), dateofhire);
	}

	/**
	 * @return value of Bonus
	 */
	public final java.math.BigDecimal getBonus()
	{
		return getBonus(getContext());
	}

	/**
	 * @param context
	 * @return value of Bonus
	 */
	public final java.math.BigDecimal getBonus(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Bonus.toString());
	}

	/**
	 * Set value of Bonus
	 * @param bonus
	 */
	public final void setBonus(java.math.BigDecimal bonus)
	{
		setBonus(getContext(), bonus);
	}

	/**
	 * Set value of Bonus
	 * @param context
	 * @param bonus
	 */
	public final void setBonus(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal bonus)
	{
		getMendixObject().setValue(context, MemberNames.Bonus.toString(), bonus);
	}

	/**
	 * @return value of EmployeeId
	 */
	public final java.lang.Long getEmployeeId()
	{
		return getEmployeeId(getContext());
	}

	/**
	 * @param context
	 * @return value of EmployeeId
	 */
	public final java.lang.Long getEmployeeId(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.Long) getMendixObject().getValue(context, MemberNames.EmployeeId.toString());
	}

	/**
	 * Set value of EmployeeId
	 * @param employeeid
	 */
	public final void setEmployeeId(java.lang.Long employeeid)
	{
		setEmployeeId(getContext(), employeeid);
	}

	/**
	 * Set value of EmployeeId
	 * @param context
	 * @param employeeid
	 */
	public final void setEmployeeId(com.mendix.systemwideinterfaces.core.IContext context, java.lang.Long employeeid)
	{
		getMendixObject().setValue(context, MemberNames.EmployeeId.toString(), employeeid);
	}

	/**
	 * @return value of Employee_Department
	 */
	public final hr.proxies.Department getEmployee_Department() throws com.mendix.core.CoreException
	{
		return getEmployee_Department(getContext());
	}

	/**
	 * @param context
	 * @return value of Employee_Department
	 */
	public final hr.proxies.Department getEmployee_Department(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		hr.proxies.Department result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Employee_Department.toString());
		if (identifier != null)
			result = hr.proxies.Department.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Employee_Department
	 * @param employee_department
	 */
	public final void setEmployee_Department(hr.proxies.Department employee_department)
	{
		setEmployee_Department(getContext(), employee_department);
	}

	/**
	 * Set value of Employee_Department
	 * @param context
	 * @param employee_department
	 */
	public final void setEmployee_Department(com.mendix.systemwideinterfaces.core.IContext context, hr.proxies.Department employee_department)
	{
		if (employee_department == null)
			getMendixObject().setValue(context, MemberNames.Employee_Department.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Employee_Department.toString(), employee_department.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return employeeMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final hr.proxies.Employee that = (hr.proxies.Employee) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Hr.Employee";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
